CREATE DATABASE OPEN_AI_DB;

-- EMOTION_RECOGNITION
create or replace schema OPEN_AI_DB.EMOTION_RECOGNITION;

--CREATE NEW STAGE
create stage RAW_DATA_SET;

--ENABLE DIRECTORY ON STAGE
alter stage RAW_DATA_SET
set directory = (enable = true);
alter stage RAW_DATA_SET refresh;

create or replace TABLE OPEN_AI_DB.EMOTION_RECOGNITION.TB_CUSTOMER_AUDIO_SENTIMENTS (
	UUID VARCHAR(16777216) NOT NULL,
	FILE_NAME VARCHAR(16777216) NOT NULL,
	AUDIO_TRANSCRIPT VARCHAR(16777216) NOT NULL,
	AUDIO_TRANSCRIBE VARCHAR(16777216) NOT NULL,
	SENTIMENT_SCORE VARCHAR(16777216) NOT NULL,
	LOAD_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_1 primary key (UUID)
);